development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: shihtzu
  pool: 5
  username: shihtzu
  password: shihtzu
  socket: /tmp/mysql.sock

production:
  host: env['DW_HOST']
  adapter: mysql2
  encoding: utf8
  database: env['DW_DB']
  pool: 5
  username: env['DW_USER']
  password: env['DW_PWD']
  socket: /var/lib/mysql/mysql.sock
  reconnect: true
